name: KitBattlePatch
main: com.battleasya.kbpatch.KBPatch
version: ${version}
api-version: 1.14
author: Dennie
website: http://battleasya.com
description: Patches KitBattle Exploits.
depend: [KitBattle]
commands:
  kbpatch:
    description: General Commands.
    aliases: [kitbattlepatch]
permissions:
  kbpatch.*:
    default: op
    children:
      kbpatch.reload: true
      kbpatch.bypass: true