############################################################
# +------------------------------------------------------+ #
# |                   KitBattle Patch                    | #
# +------------------------------------------------------+ #
############################################################

version: "1.0.1"

# This plugin is dedicated to addressing 2 well-known KitBattle exploits.
# While the fixes are straightforward, the exploits themselves are rather intricate.

# Note that this plugin is specially made for use with a KitBattle Advanced instance.
# https://www.spigotmc.org/resources/kitbattle-advanced.2872/

# For details of the exploits, you may refer to our Spigot Page:
# https://www.spigotmc.org/resources/112496/

# Please be aware that this plugin is not officially affiliated with KitBattle Advanced.
# We are simply enthusiastic KitBattle fans committed to resolving some of the issues.

# Patched By Dennie


############################################################
# +------------------------------------------------------+ #
# |                   Scope of Action                    | #
# +------------------------------------------------------+ #
############################################################

# In this section, you can specify the list of worlds where this plugin operates on.
# Simply include all the worlds where your KitBattle arenas are located to this list.

world:
  - "pvp"


############################################################
# +------------------------------------------------------+ #
# |                   Iron Fist Patch                    | #
# +------------------------------------------------------+ #
############################################################

# Undoubtedly the most long-lasting KitBattle exploit, Iron Fist (a.k.a. Damage Bug) has
# gained notoriety for allowing sword damage from a previously selected kit to persist
# even after a player logs out and back in.

# To effectively mitigate this problem, consider switching the kit selector to a sword item.
# This can be done by navigating to KitBattle's config.yml and modify the kit selector item
# as illustrated below:
# Hotbar-Items:
#   Kit-Selector:
#     item: 'DIAMOND_SWORD : name:&7Kit Selector (&aRight click!&7)'
# Other viable sword options include WOODEN_SWORD, STONE_SWORD, IRON_SWORD, and GOLD_SWORD.

# Very unfortunately, this is still not sufficient to completely rule out this exploit since
# abuser can easily bypass the kit selector with the "/kb selectkit" command.

# Enabling the "block-kb-selectkit" option disables entirely the "/kb selectkit" command
# together with all its associated aliases.

# Note: The "kbpatch.bypass" permission grants the ability to bypass this patch.

block-kb-selectkit:
  enable: true
  message: "&3[&bKBPatch&3] &7This command has been disabled!"



# Apart from changing the kit selector, we do offer an alternative solution to address
# this exploit. The following patch effectively prevents any items in the inventory from
# being moved when the kit selector item is present. Consequently, players are compelled
# to exclusively click on the kit selector in slot 1 to select a kit, thereby eliminating
# the bug.

# Note: The "kbpatch.bypass" permission grants the ability to bypass this patch.
# This permission is particularly useful for admins, as the inability to move items within
# the inventory can be inconvenient when editing the arenas.

iron-fist-patch:
  # DO NOT enable this patch if you already have XXX_SWORD as your kit selector item.
  # In general, DO NOT enable this patch if your kit selector item is a kit item.
  enable: true
  # The default kit-selector item for KitBattle is CHEST.
  kit-selector: "CHEST"



############################################################
# +------------------------------------------------------+ #
# |                   Smuggling Patch                    | #
# +------------------------------------------------------+ #
############################################################

# Smuggling (a.k.a. Teleport Bug) enables players to conveniently transport kit items
# between arenas, resulting in the possession of items from multiple kits, thereby
# disrupting the game balance.

# Practical use includes: transporting kit items from a normal arena into a kit-locked
# challenge arena, or transporting previously used kit items back into the arena.

# This patch effectively resolves this issue by removing all items from your cursor and
# crafting inventory upon teleportation.

# Note: The "kbpatch.bypass" permission grants the ability to bypass this patch.

smuggling-patch:
  enable: true


############################################################
# +------------------------------------------------------+ #
# |                   General Messages                   | #
# +------------------------------------------------------+ #
############################################################

no-permission: "&3[&bKBPatch&3] &7You don't have permission to do this!"
incorrect-syntax: "&3[&bKBPatch&3] &7Unknown command!"
reload-config: "&3[&bKBPatch&3] &7Config reloaded!"